services:
  
  restic:
    build:
      context: .
      dockerfile: Dockerfile
    image: eqe-lab/restic:latest
    volumes:
      - ./config:/config
      - ./data:/data
    environment:
      EXEC_INTERVAL_MINUTE: 10
      RUN_ON_STARTUP: true
      RESTIC_USER_FILE: /run/secrets/USERNAME
      RESTIC_PASSWORD_FILE: /run/secrets/PASSWORD
      # DEBUG: true
      RESTIC_HOST: restic-lab.phys.ethz.ch
    secrets:
      - USERNAME
      - PASSWORD

secrets:
  USERNAME:
    file: ./secrets/USERNAME
  PASSWORD:
    file: ./secrets/PASSWORD

      